language: php
php:
  - 5.6
  - 7.0

sudo: false

cache:
   directories:
     - $HOME/.composer/cache/files

before_script:
    - git clone https://github.com/shopware/shopware.git /tmp/shopware
    - cd /tmp/shopware
    # changes to the latest tag
    - git checkout $(git describe --tags `git rev-list --tags --max-count=1`)

    - mv /home/travis/build/shopware/SwagConnect /tmp/shopware/engine/Shopware/Plugins/Local/Backend/SwagConnect
    - cd /tmp/shopware/engine/Shopware/Plugins/Local/Backend/SwagConnect
    - mkdir -p build/logs
    - composer install
    - ./vendor/shopware/plugin-dev-tools/install.sh
    - ln -s vendor/shopware/plugin-dev-tools/psh56.phar psh56
    - ./psh56 travis:init

script: ./psh56 travis:unit-coveralls

notifications:
    email: false

after_success:
  - travis_retry ./psh56 travis:send-coverall-report