language: php
php:
  - 5.3

sudo: false

before_script:
    - cd /tmp
    - wget http://releases.s3.shopware.com.s3.amazonaws.com/install_4.3.2_e6d1f12c47e61fa1c10893665234cf13b6b3e9f0.zip
    - unzip install_4.3.2_e6d1f12c47e61fa1c10893665234cf13b6b3e9f0.zip -d shopware
    - rm -rf /tmp/shopware/engine/Shopware/Plugins/Default/Backend/SwagBepado
    - cd /tmp/shopware
    - mv /home/travis/build/shopware/SwagBepado /tmp/shopware/engine/Shopware/Plugins/Local/Backend
    - ls engine/Shopware/Plugins/Local/Backend
    - php bin/console sw:plugin:list
    - php bin/console sw:plugin:install SwagBepado
    - php bin/console sw:plugin:activate SwagBepado
    - cd /tmp/shopware/engine/Shopware/Plugins/Default/Backend/SwagBepado

script: phpunit
