language: php
php:
#  - 5.4
#  - 5.5
  - 5.6
  - 7.0

sudo: false

before_script:
    - git clone https://github.com/shopware/shopware.git /tmp/shopware
    - rm -rf /tmp/shopware/engine/Shopware/Plugins/Default/Backend/SwagConnect
    - cd ..
    - cd /tmp/shopware
    - ant -f build/build.xml -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
    - mv /home/travis/build/shopware/SwagConnect /tmp/shopware/engine/Shopware/Plugins/Local/Backend
    - cd /tmp/shopware
    - ls engine/Shopware/Plugins/Local/Backend
    - php bin/console sw:plugin:refresh
    - php bin/console sw:plugin:list
    - php bin/console sw:plugin:install SwagConnect
    - php bin/console sw:plugin:activate SwagConnect
    - php bin/console sw:generate:attributes
    - php bin/console orm:generate:proxies
#    - bash cache/clear_cache.sh
    - cd /tmp/shopware/engine/Shopware/Plugins/Local/Backend/SwagConnect

script: phpunit

notifications:
    email: false
