language: php
php:
#  - 5.4
#  - 5.5
  - 5.6
  - 7.0

sudo: false

before_script:
    - git clone https://github.com/shopware/shopware.git /tmp/shopware
    - rm -rf /tmp/shopware/engine/Shopware/Plugins/Default/Backend/SwagConnect
    - cd ..
    - cd /tmp/shopware
    # changes to the latest tag
    - git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
    # checkout tag v5.2.16, because v5.2.17 contains image optimizers and tests are failing
    # we have to fix that
#    - git checkout v5.2.16

    - ant -f build/build.xml -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
    - mv /home/travis/build/shopware/SwagConnect /tmp/shopware/engine/Shopware/Plugins/Local/Backend
    - cd /tmp/shopware
    - ls engine/Shopware/Plugins/Local/Backend
    - php bin/console sw:plugin:refresh
    - php bin/console sw:plugin:list
    - php bin/console sw:plugin:install SwagConnect
    - php bin/console sw:plugin:activate SwagConnect
    - php bin/console sw:generate:attributes
    - php bin/console orm:generate:proxies
    - php bin/console sw:cache:clear --env=testing
    - cd /tmp/shopware/engine/Shopware/Plugins/Local/Backend/SwagConnect

script: ../../../../../../vendor/bin/phpunit

notifications:
    email: false
